# Generated by Django 3.2 on 2021-08-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210826_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.personal'),
        ),
    ]
